config/routes.rb
Rails.application.routes.draw do
  # apiコントローラのルーティング
  namespace :api, { format: 'json' } do
    namespace :v1 do
      # デバイスコントローラはデバイスの名前の取得とレコードの登録に使う
      resources :devices, :only => [:index, :show, :create, :destroy] do
        collection do
          post ':id/records', to: 'devices#create_records'
        end
      end
      # レコードコントローラは読み取り専用，レコードの登録はデバイスコントローラから
      resources :records, :only => [:index, :show]
      # マップコントローラ
      resources :maps, :only => [:index, :show, :create] do
        collection do
          get 'download', to: 'maps#download'
        end
      end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    end
  end
  resources :maps
  resources :devices, :only => :show

end

app/models/device.rb
class Device < ApplicationRecord
  has_many :records
  accepts_nested_attributes_for :records, allow_destroy: true
end

app/controllers/api/v1/devices_controller.rb
module Api
  module V1
    class DevicesController < ApplicationController
      before_action :set_device, only: [:show, :destroy, :create_records]
      protect_from_forgery :except => [:create, :create_records]
      # GET /api/v1/devices.json
      def index
        @devices = Device.all
      end

      # GET /api/v1/devices/1.json
      def show
      end

      # POST /api/v1/devices.json
      def create
        device_params_tmp = device_params
        # すでにある名前かチェック
        @device = Device.find_by(name: device_params_tmp[:name])
        if @device.nil?
          # 新しい名前の場合の処理
          @device = Device.new(device_params_tmp)
          respond_to do |format|
            if @device.save
              format.html { redirect_to @device, notice: 'Device was successfully created.' }
              format.json { render :show, status: :created, location: @device }
            else
              format.html { render :new }
              format.json { render json: @device.errors, status: :unprocessable_entity }
            end
          end
        else
          # すべにある場合の処理
          render :show, status: :created, location: @device
        end
      end

      # DELETE /api/v1/devices/1.json
      def destroy
        @device.destroy
        respond_to do |format|
          format.html { redirect_to devices_url, notice: 'Device was successfully destroyed.' }
          format.json { head :no_content }
        end
      end

      # POST /api/v1/devices/1/records.json
      def create_records
        params[:device][:records_attributes].each do |record_params|
          logger.debug record_params
          record = Record.new(record_params.permit(:time, :major, :rssi))
          record[:device_id] = @device.id
          record.save
        end
        render :json => @device
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_device
          @device = Device.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def device_params
          params.require(:device).permit(:name, records_attributes: [:time, :major, :rssi])
        end

    end
  end
end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_with(model: device, local: true) do |form| %>
  <% if device.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% device.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :device_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/devices/edit.html.erb
<h1>Editing Device</h1>

<%= render 'form', device: @device %>

<%= link_to 'Show', @device %> |
<%= link_to 'Back', devices_path %>

app/views/devices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Devices</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @devices.each do |device| %>
      <tr>
        <td><%= device.name %></td>
        <td><%= link_to 'Show', device %></td>
        <td><%= link_to 'Edit', edit_device_path(device) %></td>
        <td><%= link_to 'Destroy', device, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Device', new_device_path %>

app/views/devices/new.html.erb
<h1>New Device</h1>

<%= render 'form', device: @device %>

<%= link_to 'Back', devices_path %>

app/views/devices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @device.name %>
</p>

<%= link_to 'Edit', edit_device_path(@device) %> |
<%= link_to 'Back', devices_path %>