config/routes.rb
Rails.application.routes.draw do
  # apiコントローラのルーティング
  namespace :api, { format: 'json' } do
    namespace :v1 do
      # デバイスコントローラはデバイスの名前の取得とレコードの登録に使う
      resources :devices, :only => [:index, :show, :create, :destroy] do
        collection do
          post ':id/records', to: 'devices#create_records'
        end
      end
      # レコードコントローラは読み取り専用，レコードの登録はデバイスコントローラから
      resources :records, :only => [:index, :show]
      # マップコントローラ
      resources :maps, :only => [:index, :show, :create] do
        collection do
          get 'download', to: 'maps#download'
        end
      end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
    end
  end
  resources :maps
  resources :devices, :only => :show

end

app/models/map.rb
class Map < ApplicationRecord
  mount_base64_uploader :image, ImageUploader
  has_many :beacons
end

app/controllers/api/v1/maps_controller.rb
require 'base64'
module Api
  module V1
    class MapsController < ApplicationController
      before_action :set_map, only: [:show, :edit, :update, :destroy]
      protect_from_forgery :except => [:create]
      # GET /api/v1/maps
      # GET /api/v1/maps.json
      def index
        unless params[:major].blank?
          # major値を指定することで，そのmajor値を持つビーコンが存在するフロア情報をまとめて返す．
          beacon = Beacon.find_by(major: params[:major])
          unless beacon.nil?
            map = Map.find(beacon.map_id)
            payload = {}
            payload[:is_exist] = "true"
            payload[:map_id] = beacon.map_id
            payload[:beacons] = map.beacons.select(:major, :x, :y, :id)
            render :json => payload
          else
            payload = {}
            payload[:is_exist] = "false"
            render :json => payload
          end
        else
          @maps = Map.all
        end
      end

      # GET /api/v1/maps/1
      # GET /api/v1/maps/1.json
      def show
      end

      # GET /api/v1/maps/new
      def new
        @map = Map.new
      end

      # GET /api/v1/maps/1/edit
      def edit
      end

      # POST /api/v1/maps.json
      def create
        @map = Map.new(map_params)

        respond_to do |format|
          if @map.save
            format.html { redirect_to @map, notice: 'Map was successfully created.' }
            format.json { render :show, status: :created, location: @map }
          else
            format.html { render :new }
            format.json { render json: @map.errors, status: :unprocessable_entity }
          end
        end
      end

      # PATCH/PUT /api/v1/maps/1.json
      def update
        respond_to do |format|
          if @map.update(map_params)
            format.html { redirect_to @map, notice: 'Map was successfully updated.' }
            format.json { render :show, status: :ok, location: @map }
          else
            format.html { render :edit }
            format.json { render json: @map.errors, status: :unprocessable_entity }
          end
        end
      end

      # DELETE /api/v1/maps/1.json
      def destroy
        @map.destroy
        respond_to do |format|
          format.html { redirect_to maps_url, notice: 'Map was successfully destroyed.' }
          format.json { head :no_content }
        end
      end

      # GET /api/v1/maps/download.json
      def download
        # IDかNAMEをパラメータで指定する
        if not params[:id].blank?
          @map = Map.find(params[:id])
        elsif not params[:name].blank?
          @map = Map.find_by(name: params[:name])
        else
          render :json => {}
        end

        if @map.nil?
          render :json => {}
        else
          payload = {}
          encoded_string = Base64.encode64(File.open(@map.image.path, "rb").read)
          payload[:base64] = encoded_string
          payload[:name] = @map.name
          render :json => payload
        end
      end

      private
        # Use callbacks to share common setup or constraints between actions.
        def set_map
          @map = Map.find(params[:id])
        end

        # Never trust parameters from the scary internet, only allow the white list through.
        def map_params
          params.require(:map).permit(:name, :image, :image_cache, :remove_image)
        end
    end
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController
  before_action :set_map, only: [:show, :edit, :update, :destroy]
  protect_from_forgery :except => [:create]
  # GET /api/v1/maps
  # GET /api/v1/maps.json
  def index
    @maps = Map.all
  end

  # GET /api/v1/maps/1
  # GET /api/v1/maps/1.json
  def show
  end

  # GET /api/v1/maps/new
  def new
    @map = Map.new
  end

  # GET /api/v1/maps/1/edit
  def edit
  end

  # POST /api/v1/maps.json
  def create
    @map = Map.new(map_params)

    respond_to do |format|
      if @map.save
        format.html { redirect_to @map, notice: 'Map was successfully created.' }
        format.json { render :show, status: :created, location: @map }
      else
        format.html { render :new }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /api/v1/maps/1.json
  def update
    respond_to do |format|
      if @map.update(map_params)
        format.html { redirect_to @map, notice: 'Map was successfully updated.' }
        format.json { render :show, status: :ok, location: @map }
      else
        format.html { render :edit }
        format.json { render json: @map.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /api/v1/maps/1.json
  def destroy
    @map.destroy
    respond_to do |format|
      format.html { redirect_to maps_url, notice: 'Map was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_map
      @map = Map.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def map_params
      params.require(:map).permit(:name, :image)
    end
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/views/maps/_form.html.erb
<%= form_with(model: map, local: true) do |form| %>
  <% if map.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(map.errors.count, "error") %> prohibited this map from being saved:</h2>

      <ul>
      <% map.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :map_name %>
  </div>

  <!-- 追加箇所 開始 -->
  <div class="field">
    <% if @image.image? %>
      <div class="thumbnail">
        <%= image_tag @image.image.url %>
      </div>
    <% end %><br>
    <%= form.label :image %><br>
    <%= form.file_field :image %>
    <%= form.hidden_field :image_cache %>
  </div>
  <div class="field">
    <!-- 既存レコード(DBに保存されている)かつ、画像が存在する場合 -->
    <% if @image.persisted? && @image.image? %>
      <label>
        <%= form.check_box :remove_image %>
        画像を削除
      </label>
    <% end %>
  </div>
  <!-- 追加箇所 終了 -->

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/maps/edit.html.erb
<h1>Editing Map</h1>

<%= render 'form', map: @map %>

<%= link_to 'Show', @map %> |
<%= link_to 'Back', maps_path %>

app/views/maps/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Maps</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @maps.each do |map| %>
      <tr>
        <td><%= map.name %></td>
        <td><%= map.image %></td>
        <td><%= link_to 'Show', map %></td>
        <td><%= link_to 'Edit', edit_map_path(map) %></td>
        <td><%= link_to 'Destroy', map, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Map', new_map_path %>

app/views/maps/new.html.erb
<h1>New Map</h1>

<%= render 'form', map: @map %>

<%= link_to 'Back', maps_path %>

app/views/maps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @map.name %>
</p>

<!-- 追加箇所 開始 -->
<p>
  <strong>Image:</strong>
  <% if @image.image? %>
    <div class="thumbnail">
      <%= image_tag @image.image.url %>
    </div>
  <% end %>
</p>
<!-- 追加箇所 終了 -->

<%= link_to 'Edit', edit_map_path(@map) %> |
<%= link_to 'Back', maps_path %>